title: "Appduplex"
description: "Supercharge WordPress to the Next Level - a premium WordPress plugin development company."
status: "In Active Development"

author-name: "i am Programmer"
author-url: "https://iamprogrammer.lk"
github-url: "https://github.com/appduplex"
x-url: "https://x.com/appduplex"
linkedin-url: "https://linkedin.com/company/appduplex"
email: "contact@appduplex.com"
